name: Build
on:
  workflow_dispatch:
  push:
    branches: [master, Swiper6, Swiper7, Swiper8]
  pull_request:
    branches: [master, Swiper6, Swiper7, Swiper8]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build:prod
